### ISSUE TITLE
ClimateDevice is deprecated, modify MitsubishiClimate to extend ClimateEntity

### ISSUE THREAD

**Issue by DoubleAmperSand** [scottyphillips/mitsubishi_hass#10]
After updating HAS to 0.110 I now see the below warning in the log

2020-05-25 06:55:10 WARNING (MainThread) [homeassistant.components.climate] ClimateDevice is deprecated, modify MitsubishiClimate to extend ClimateEntity

**Comment by scottyphillips** [comment]
Thanks I’ll look into it.

**Comment by suiciety** [comment]
I'm on .110 and see this same issue however it's working ok, great work. I like this local control a lot more than the net based version

I can also report that this is working fine with the MSZ-GE35VAD wall mounted unit. I'll also be hooking up our ducted system which youve already listed as compatible.

**Comment by scottyphillips** [comment]
The Experimental build now extends 'ClimateEntity'
