### ISSUE TITLE
The power button on the heat pump control will not turn on the heat pump.

### ISSUE THREAD

**Issue by FrancisCarmine** [scottyphillips/mitsubishi_hass#13]
While testing #12  when the system is turned off it cannot be turned on by the power button in Home Assistant as highlighted below.  If I use the Mitsubishi app the system powers up nicely and its new status shows correctly in Home Assistant.  The HA power button will shut down the system without problems so it seems like its only when turning the system on - maybe related to difference between off and standby?

![image](https://user-images.githubusercontent.com/32243958/86870744-10564600-c12d-11ea-8ce1-dad9117dc205.png)

**Comment by scottyphillips** [comment]
I think that is actually Home Assistant Lovelace behaviour - climate.on() I am pretty sure works fine but I will have a look some other time. Pressing the various climate buttons will turn on the system as well.

**Comment by FrancisCarmine** [comment]
No you are right, looks like the power button is only intended to turn it off.  It fires up when you press one of the other icons straight into that mode - which makes sense I guess.
