### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by oneseventhree** [scottyphillips/mitsubishi_hass#14]
Great, great, great and GREAT work on this!

Thank you so much.

Any chance you will get it added to HACS?

👍

**Comment by scottyphillips** [comment]
I don’t use HACS much (don’t have it installed at the moment but it should be already on there!!! 
![474E3452-88ED-4019-B734-0BB9AACD81F3](https://user-images.githubusercontent.com/26150540/88375265-9c7b9500-cdde-11ea-8f7f-66ad41c515d2.jpeg)

**Comment by oneseventhree** [comment]
That's really strange! Because:
![Untitled](https://user-images.githubusercontent.com/15043282/88375780-8de1ad80-cddf-11ea-99f2-fd8eff5ea1c0.png)

**Comment by khcnz** [comment]
It's definitely in HACS - I've installed it through there - it's listed as 

"Mitsubishi Echonet Climate and Sensor Component"
