### ISSUE TITLE
swing mode implemented?

### ISSUE THREAD

**Issue by carlito1979** [scottyphillips/mitsubishi_hass#17]
Hi,

I can see that it looks like the swing modes were implemented in the python code, but was this then pulled into the hass custom component? What would I need to do to get swing modes working in home assistant?

**Comment by scottyphillips** [comment]
I have no way of testing swing mode but i believe @khcnz was playing around with it

**Comment by carlito1979** [comment]
Hi @scottyphillips. I added in some new code in both the mitsibushi_hass and mitsibushi_echo implementations to get swing mode working nicely in Home Assistant. It's a bit clunky but it allows a user to choose from a list of preset vertical and horizontal swing modes. I'm not familiar with sharing code in github but I could submit them if you like. I can confirm they work, but as I said it's a bit clunky owing to the fact that HA only has one swing mode field and two of my heat pumps have both vertical and horizontal swing modes.

**Comment by Yanoflies** [comment]
> they work, but as I said it's a bit clunky owing to the fact that HA only has one swing mode field and two of my heat pumps have both vertical and horizontal swing modes.

Could I have a look at your code please? I'd like to implement swinging for my units.

**Comment by carlito1979** [comment]
> > they work, but as I said it's a bit clunky owing to the fact that HA only has one swing mode field and two of my heat pumps have both vertical and horizontal swing modes.
> 
> Could I have a look at your code please? I'd like to implement swinging for my units.

I'll look at sharing my code later tonight (NZ time) as I'm at work. I've got it working with both my vertical only unit and the two units that have both vertical and horizontal but yeah as you say HA is pretty clunky so the way I've implemented it was to only expose some preset options (e.g. "Vert Auto | Horiz Swing" or "Vert Upper | Horiz Center").
It required changes to both this hass module and the echonet python module.

**Comment by jpillora** [comment]
👍 Also interested in getting swing mode into HA

**Comment by Yanoflies** [comment]
> > > they work, but as I said it's a bit clunky owing to the fact that HA only has one swing mode field and two of my heat pumps have both vertical and horizontal swing modes.
> > 
> > 
> > Could I have a look at your code please? I'd like to implement swinging for my units.
> 
> I'll look at sharing my code later tonight (NZ time) as I'm at work. I've got it working with both my vertical only unit and the two units that have both vertical and horizontal but yeah as you say HA is pretty clunky so the way I've implemented it was to only expose some preset options (e.g. "Vert Auto | Horiz Swing" or "Vert Upper | Horiz Center").
> It required changes to both this hass module and the echonet python module.

If you have the chance then please share. 👍

**Comment by Yanoflies** [comment]
Anyone has any update on Swing Mode?

**Comment by khcnz** [comment]
I haven't quite got around to writing any code, but it should be pretty straight forward I think the econet library now returns all the info needed? Is this just a small mapping change? My units do support it so I'm happy to help test etc if anyone has a proposed PR..

**Comment by carlito1979** [comment]
I have working code that I've been using for 6 months but it's quite ugly and because Home Assistant only allows one swing field it gets quite messy if you have units that have both horizontal and vertical swing modes. One of my units has up to 30 different vertical/horizontal mode combinations so I was keen to avoid having all 30 in a dropdown list and/or icons in HA!
I've got a half finished rewrite that makes it simpler to set available swing modes in your config.yaml but I haven't found time to finish it yet. I'll try and get back into the right frame of mind to finish and then share here in the next couple of weeks,

**Comment by scottyphillips** [comment]
Sorry team count me out here ive got a ducted system, but if we do get some code for it i think running a seperate branch for the time to test it extensively would be appropriate.

**Comment by carlito1979** [comment]
question for you perhaps @scottyphillips (because I'm pretty clueless about github) but as the swing mode implementation requires changes to both mitsubishi_hass and mitsubishi_echonet what would I need to do to ensure the separate hass branch references the separate echonet branch?

**Comment by scottyphillips** [comment]
umm good question. maybe just raise PRs for both in each respective repo and we can have a look at what the differences are between both.

**Comment by khcnz** [comment]
> I have working code that I've been using for 6 months but it's quite ugly and because Home Assistant only allows one swing field it gets quite messy if you have units that have both horizontal and vertical swing modes. One of my units has up to 30 different vertical/horizontal mode combinations so I was keen to avoid having all 30 in a dropdown list and/or icons in HA!
> I've got a half finished rewrite that makes it simpler to set available swing modes in your config.yaml but I haven't found time to finish it yet. I'll try and get back into the right frame of mind to finish and then share here in the next couple of weeks,

As a **quick win**, it will be super easy to let people figure out which combinations or vertical and horizontal they would want in a list something like this?
swing
- upper_left
- lower_right

That could be parsed with the _ and sent over to eco library?

**Comment by scottyphillips** [comment]
It’s sounding like a limitation of Home Assistant itself.  May I suggest that peeps who are impacted raise a feature request with Home Assistant to implement both horizontal and vertical swing modes?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by khcnz** [comment]
Somewhat relevant thread https://github.com/home-assistant/architecture/issues/22#issuecomment-475039527 and actually a PR here to HA https://github.com/home-assistant/architecture/discussions/553

**Comment by scottyphillips** [comment]
@khcnz latest HA has a new 'select' entity. We could create up to three 'select entities':
* swing modes (auto etc)
* horizontal swing
* vertical swing

https://www.home-assistant.io/blog/2021/07/07/release-20217/#new-entity-select

**Comment by scottyphillips** [comment]
I have implemented the horizontal and vertical swing modes as select entities. You will need to be running Home Assistant 2021.07.01 or later to use select entities. 

The 'pychonet' branch has a brand new 'echonetlite' custom component. This centralises the API calls at a platform level. No more flooding API calls which means better overall performance. As added bonuses it now uses GUI based config entries to configure - no more YAML - and provides select entities for horizontal and vertical swing modes! Give it a try!

Install the 'echonetlite' folder into 'custom_components' and reload Home Assistant.
You may also need to clear your browser cache.
Go to configuration -> integrations -> ADD INTEGRATION.
Select the 'echonetlite' integration. Enter your IP address in the host field and give the platform a name.

It SHOULD automatically configure the climate entry, sensors and any select entities for both horizontal and vertical swing modes.
This should hopefully be enough of a carrot to get people looking at the new branch!

**Comment by jpillora** [comment]
Awesome news, nice work Scott - will test it out tomorrow and report back

**Comment by carlito1979** [comment]
Hi @scottyphillips awesome work. I've installed echonetlite to try it out and I love how much easier it is to set up and configure my heat-pumps.
For context I have 3 wall mounted Mitsubishi heat-pumps all with wifi connectivity
MSZ-AP20VGD
      vertical swing only
      6 fan speeds: auto, minimum, low, medium-low, medium-high, high
MSZ-AP25VGD
      horizontal and vertical swing modes
      6 fan speeds: auto, minimum, low, medium-low, medium-high, high
MSZ-AP60VG
      horizontal and vertical swing modes
      7 fan speeds: auto, minimum, low, medium-low, medium, medium-high, high

Some observations and potential builds from my initial testing

1.  The heat-pumps are all reporting the full set of fan modes but I know from my own testing that they only have the settings I have listed above. I think this is a limitation of the reporting in echonet so it would be good if we could still manually specify which fan modes are displayed/used in Home Assistant
2. Using the select entity with the horizontal and vertical modes works well - setting up the AP20 did not create a horizontal entity. However like fan modes it is bringing back all the modes even if the unit doesn't support them. For example the AP25 can't do split horizontal airflow (left-right mode) but the AP60 can. Once again it would be good if we could specify which modes to display/use in HA. Even better if we could rename them as left-right isn't terribly elegant
3. The HA climate entity does allow for swing modes and I had a very crude implementation working based on your work that allowed me to control my units. This new implementation you've done is much better but can I suggest rather than using the select entities for both swing modes it would be more useful if you implemented the climate swing mode for the vertical modes? This then integrates the most common swing mode directly into most climate entity control cards in lovelace. Users could then use vertical as a separate select entity where required
4. Last observation I promise! The select entities don't allow for auto or continuous swing modes. These require setting SWING_MODE and AUTO_DIRECTION modes in conjunction with the AIRFLOW_VERT & AIRFLOW_HORIZ modes. Is there any way to add Auto and Swing into the select entities? Again I had a working solution based on your previous code but it is ugly trying to control both vertical and horizontal modes from one drop-down. The AP60 for example would have 49 different options if I showed them all in that one swing mode dropdown!

Anyways I hope that helps and I hope I've been clear enough. I'm happy to help test. I'd contribute if I could but my level of coding ability is pretty low and I've never contributed to a git project before.

**Comment by scottyphillips** [comment]
Hey mate, all that stuff you have mentioned should be pretty easy to sort out. I can probably sort it out tonight. I’m glad it’s working well so far I’ve spent almost all day ironing out the bugs!!! Are you using the very latest update?

**Comment by carlito1979** [comment]
Hey @scottyphillips whoops looks like we've got a syntax error in one of the files - see the error report below

![image](https://user-images.githubusercontent.com/13175554/125934737-848ad8fb-ac58-402a-9d1a-08d7fe10927b.png)

**Comment by carlito1979** [comment]
Okay I fixed that minor syntax error and got the component to run but now I've lost the select entities completely

Logger: homeassistant.components.select
Source: custom_components/echonetlite/select.py:38
Integration: Select (documentation, issues)
First occurred: 10:37:46 PM (6 occurrences)
Last logged: 10:43:24 PM

Error while setting up echonetlite platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/echonetlite/select.py", line 20, in async_setup_entry
    entities.append(EchonetSelect(hass, entity['API'], config,
  File "/config/custom_components/echonetlite/select.py", line 38, in __init__
    self._attr_current_option = self._instance._update_data[self._codeword]
KeyError: 'Automatic control of air flow direction setting'

**Comment by scottyphillips** [comment]
ive pushed some code which fixes the syntax errors can you try running that please

**Comment by carlito1979** [comment]
Sorry had to go to bed.
New error message now

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:429
Integration: Climate (documentation, issues)
First occurred: 7:14:01 AM (6 occurrences)
Last logged: 7:14:01 AM

Error adding entities for domain climate with platform echonetlite
Error while setting up echonetlite platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 242, in capability_attributes
    data[ATTR_SWING_MODES] = self.swing_modes
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 429, in swing_modes
    return self._attr_swing_modes
AttributeError: 'EchonetClimate' object has no attribute '_attr_swing_modes'

**Comment by carlito1979** [comment]
Found the error and fixed it at my end so I can confirm the vertical swing mode correctly pulls through
Needed to add the following to the climate.py code
    @property
    def swing_modes(self):
        """Return the list of available swing modes."""
        return self._swing_modes

**Comment by carlito1979** [comment]
Hi @scottyphillips. I couldn't get the select entities to work correctly. They will show changes but they don't appear to handle making changes themselves. The relationship between the AUTO_DIRECTION, SWING_MODE, AIFRLOW_VERT & AIRFLOW_HORIZ is a bit complicated.

I spent a bit of time today modifying the code and I have a working implementation which I have forked. I also realised today that the HA Climate entity provides a mode (PRESET) which can be customised. I have used this to control the Horizontal Swing functions on compatible heat-pumps. I wish I'd thought of this earlier!
I use a custom lovelace card (simple-thermostat) which allows me to customise the heatpump controls so the Preset modes shows as "Horizontal" instead so it is less confusing when using HA to control the heat-pumps.

Anyways - have a look and hopefully there's something of use for you there.

**Comment by scottyphillips** [comment]
To be honest ive spent a ton of time on this today but hadn't had a chance to push a new branch. I dont think the select entities were working correctly in the last update. Ive pushed updated code now, can you please test again and just advise of any issues.

**Comment by scottyphillips** [comment]
Okay the latest nightly push is done!

**Comment by carlito1979** [comment]
Have tested and it looks like the select entities work correctly now. Nice work @scottyphillips!
I have forked and included my code to merge auto and continuous swing modes directly into the Vertical and Horizontal modes for the Climate entity but that's just for my own use.

**Comment by jpillora** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/633843/126056593-36b09b3b-a7f1-4e2a-889c-a236500dca7e.png">

Is it possible to install via HACS UI? Beta?

**Comment by scottyphillips** [comment]
No not yet I’m not ready to deploy to HACS. The integration will end up with a new name and repo location.

Scott

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scottyphillips** [comment]
im closing this issue as 'pychonet-2.0' fully implements swing modes as selects, but I need more testers before I declare the branch stable enough moving forward.
