### ISSUE TITLE
HASS verson 2021.3.4 reports 'no version'

### ISSUE THREAD

**Issue by girkers** [scottyphillips/mitsubishi_hass#20]
I love this integration it is awesome, but the aforementioned version of HASS is reporting this in my log file:

 No 'version' key in the manifest file for custom integration 'mitsubishi'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'mitsubishi'

**Comment by DickSwart** [comment]
same here

**Comment by scottyphillips** [comment]
ive made a minor change and this should be fixed now
