### ISSUE TITLE
Breaks Models SLZ-KF25VA3, SLZ-KF35VA3, and SLZ-KF50VA3

### ISSUE THREAD

**Issue by ChirpyTurnip** [scottyphillips/mitsubishi_hass#25]
Hi,

New version breaks my integration for outside temperature on my heat pumps (models SLZ-KF25VA3, SLZ-KF35VA3, and SLZ-KF50VA3). Inside temperature reading and controls still appear to function. 

Will roll back to the previous version as that's my only outside temp sensor for now. Can re-test if on new release if that helps. 

Kind regards,
CP.

**Comment by scottyphillips** [comment]
are you using the climate or the sensor?

**Comment by ChirpyTurnip** [comment]
I'm only new to HA....so go easy because I'm still finding my feet
since starting three weeks ago.

I'm using the outside_sensor entity - it presents this three times (once
for each heat pump) but there is only one outside unit so it is just the
same thing in reality. I also vaguely recall the heat pumps showing up
under Config > Integrations but I can't see them there now...probably
because they were never there and just appear as entities in
the background.

I don't have a outside temperature climate entity:

[image: image.png]

So when I run the new version I get this:

[image: image.png]
And the log reports:

2021-06-12 14:05:10 WARNING (MainThread)
[custom_components.mitsubishi.sensor] HA requested an update from HVAC
192.168.20.22 but no data was received

The ip address in the error message is for the hallway unit which the
sensor entity I've used...

Does that help at all?

CP.

**Comment by scottyphillips** [comment]
yeah its affected me too I just hadn't realised. (ive been rebuilding my entire home assistant last 48 hours after my SD card died)

Version 2.1.2 fixes the issue.

**Comment by scottyphillips** [comment]
This should be fixed now

**Comment by ChirpyTurnip** [comment]
Mine has just gone nuts going from nothing to a lot of integrations in just
a few weeks so I've paused development to move everything to a new NUC
before I get trapped in SD Card hell....my PIs will be used a Zigbee2MQTT
hubs which should work nicely....  :-)

I've just loaded 2.1.2 - all working again!

Cheers!

**Comment by scottyphillips** [comment]
Its gets a little addictive with all the integrations…

I had to buy an SSD for my raspberry pi 4, it is performing so much better now.

I also turned down the ‘recorder’ interval settings in home assistant YAML to stop it smashing the drive so much… 

I thought about buying a NUC but I am too poor… ☹ 

 

I’m glad this has fixed your issue. 

 

 

 

From: ChirpyTurnip ***@***.***>
Reply-To: scottyphillips/mitsubishi_hass ***@***.***>
Date: Saturday, 12 June 2021 at 12:17 pm
To: scottyphillips/mitsubishi_hass ***@***.***>
Cc: Scott Phillips ***@***.***>, Comment ***@***.***>
Subject: Re: [scottyphillips/mitsubishi_hass] Breaks Models SLZ-KF25VA3, SLZ-KF35VA3, and SLZ-KF50VA3 (#25)

 

Mine has just gone nuts going from nothing to a lot of integrations in just
a few weeks so I've paused development to move everything to a new NUC
before I get trapped in SD Card hell....my PIs will be used a Zigbee2MQTT
hubs which should work nicely.... :-)

I've just loaded 2.1.2 - all working again!

Cheers!
