### ISSUE TITLE
Error loading 2.1.5

### ISSUE THREAD

**Issue by Alfiegerner** [scottyphillips/mitsubishi_hass#27]
Hi,

I'm getting no devices and the following logs on loading 2.1.5:

```
Logger: homeassistant.components.climate
Source: custom_components/mitsubishi/climate.py:68
Integration: Climate (documentation, issues)
First occurred: 8:26:33 PM (5 occurrences)
Last logged: 8:26:33 PM

Error while setting up mitsubishi platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mitsubishi/climate.py", line 47, in async_setup_platform
    entities.append(MitsubishiClimate(config.get(CONF_NAME),
  File "/config/custom_components/mitsubishi/climate.py", line 68, in __init__
    self._uid = echonet_hvac.getIdentificationNumber()["identification_number"]
AttributeError: 'HomeAirConditioner' object has no attribute 'getIdentificationNumber'
```

I have AP series heat pumps.

**Comment by scottyphillips** [comment]
Can you try updating the 'mitsubishi_echonet' library to 0.5?

**Comment by Alfiegerner** [comment]
Thanks Scotty, yes am running HACs and yes have 0.5.1 echonet library (and no others). Might try restarting the docker container.

**Comment by scottyphillips** [comment]
Yes I would try restarting everything to begin with, and then we can validate which libraries are installed to the core home assistant container with pip, do you know how to run an interactive session to a running docker container?

 

Regards,

 

Scott

 

From: Alfiegerner ***@***.***>
Reply-To: scottyphillips/mitsubishi_hass ***@***.***>
Date: Tuesday, 15 June 2021 at 6:49 pm
To: scottyphillips/mitsubishi_hass ***@***.***>
Cc: Scott Phillips ***@***.***>, Comment ***@***.***>
Subject: Re: [scottyphillips/mitsubishi_hass] Error loading 2.1.5 (#27)

 

Thanks Scotty, yes am running HACs and yes have 0.5.1 echonet library (and no others). Might try restarting the docker container.

**Comment by Alfiegerner** [comment]
Yep restarting docker container fixed it. Bit odd as I did an interactive session into the container to confirm that 0.5.1 was there, but hey ho, all working now. Thanks for everything.

**Comment by scottyphillips** [comment]
No problem, im an network engineer by trade so all troubleshooting begins with 'lets reboot' lol
