### ISSUE TITLE
HELP NEEDED - Please test 'pychonet-2.0' branch

### ISSUE THREAD

**Issue by scottyphillips** [scottyphillips/mitsubishi_hass#29]
Hi Everyone,

Ive spent the last few days rewriting the python library that powers this custom component. Basically i have refactored to to make it extensible to all sorts of ECHONET devices in the first step towards turning this into an official integration. The library has changed so much it has its own repo now 'pychonet' 

But I need your help. I need to test the custom component that makes use of 'pychonet' - I need to validate all the functionality, setting temperature values, the sensors, the works. If you can update the custom component manually to use the 'pychonet-2.0' branch and let me know of any issues then that would be appreciated.

Eventually this branch will be promoted to master and I will stop referencing and maintaining 'mitsubishi_echonet' in this integration. So any bugs found now wont trip anyone up when the time comes to promote.

Thanks everyone.

**Comment by scottyphillips** [comment]
The 'pychonet' branch has a brand new 'echonetlite' custom component. This centralises the API calls at a platform level. No more flooding API calls which means better overall performance. As added bonuses it now uses GUI based config entries to configure - no more YAML - and provides select entities for horizontal and vertical swing modes! Give it a try!

Install the 'echonetlite' folder into 'custom_components' and reload Home Assistant.
You may also need to clear your browser cache.
Go to configuration -> integrations -> ADD INTEGRATION.
Select the 'echonetlite' integration. Enter your IP address in the host field and give the platform a name. 

It SHOULD automatically configure the climate entry, sensors and any select entities for both horizontal and vertical swing modes. 
This should hopefully be enough of a carrot to get people looking at the new branch!

**Comment by Alfiegerner** [comment]
Hi @scottyphillips ,

I gave this a crack today.  Should we be looking at Pychonet branch or Pychonet-2.0?  These comments relate to testing Pychonet-2.0, but can run through other branch quickly and confirm behaviours / issues there.

I'm testing using model AP35VG, and AP25VGs which have a MAC568.  I have 2 outdoor units servicing 5 heatpumps

First  up set up and entities:
- Set up worked a charm, created climate entities, selects and sensors.
- Outdoor temp sensor works fine on units attached to one outdoor unit, but not the other (smaller one). Outdoor temp shown as disabled.
- Fan mode shows 10 options.  Previous component I had the following specified as (IIRC) they were the only ones that worked:
```
- platform: mitsubishi
    ip_address: 192.168.86.81
    name: bedroom_3
    fan_modes:
      - 'auto'
      - 'minimum'
      - 'low'
      - 'medium-low'
      - 'medium-high'
      - 'high'
```
- Swing mode shows 5 options, but none of them are Auto which I imagine is widely used.

Using the entities:
- Climate change, turning to heat  / cold etc works.
- Fan mode select doesn't trigger any changes, tried with each of them, confirmed no change in Melview android app and status returns to Auto as per app.
- Using Swing mode causes 'no attribute 'setAirflowVert'.

**Comment by scottyphillips** [comment]
If you go back to the 'integrations' section you should now be able to configure the relevant fan and swing settings. Can you go look and see if those options are available?

**Comment by Alfiegerner** [comment]
Here's a screen grab of interacting with selects from integration screen:

https://photos.app.goo.gl/vTenAEyS91c359S4A

Is the idea that we would do a 'multi-select' to get e.g fan modes?

**Comment by scottyphillips** [comment]
![Screen Shot 2021-08-09 at 10 16 09 am](https://user-images.githubusercontent.com/26150540/128649999-58bf574b-f956-450e-b133-3fb408011e3d.png)
Go back to the configuration and when you click 'configure' you should be able to fine tune your settings.
![Screen Shot 2021-08-09 at 10 16 42 am](https://user-images.githubusercontent.com/26150540/128650030-aa2bd41e-c055-4498-be1a-3a67765fe24f.png)

**Comment by Alfiegerner** [comment]
Okay got those set.  E.g.  so fan modes match previous config and all available vert positions are selected. 

Selecting a fan modes gives no errors but doesn't update heatpump.
Selecting vert position gives same no attribute error.

**Comment by scottyphillips** [comment]
its not instantaneous when the fan setting is updated and the corresponding change to the climate entity

**Comment by Alfiegerner** [comment]
Here's the vert swing attribute error:

![Screen_Recording_20210809-123157_Home Assistant_exported_2567_2](https://user-images.githubusercontent.com/596188/128650613-260f5622-c1ea-42c6-b304-59ad5490e948.jpg)

As previous version swing option wasn't available, we just left to Auto doenst look to be available here.

On setting fan mode - have left for several minutes, UI reverts back to Auto and I can see in Melview app (and being in same room as heat pump) no change taking place.

**Comment by Alfiegerner** [comment]
p.s. - have been using controls in Climate entity to test Fanmode.

**Comment by scottyphillips** [comment]
can you triple check lines 217-220 of the climate.py file thanks and confirm what they say. 
It should look like this:
```
    async def async_set_swing_mode(self, swing_mode):
        """Set new swing mode."""
        await self._connector._instance.setAirflowVert(swing_mode)
        self._connector._update_data[ENL_AIR_VERT] = swing_mode
```

**Comment by scottyphillips** [comment]
Okay, so configuring the fan setting was still using the HA asyncio executor when it no longer needs to (the library itself uses asyncio now). So ive fixed that up in the latest push.

**Comment by Alfiegerner** [comment]
Thanks @scottyphillips  - just pulled latest and all working, can select swing mode and fan mode and they work as expected.

Is there any chance you can add Auto to swing mode list?  It's really the only setting we use

Maybe it's already possible from these selects but I'm not clear how they relate to the climate entity?

![image](https://user-images.githubusercontent.com/596188/128652260-364e0e27-a23d-480d-9264-c105f1f93f31.png)

**Comment by scottyphillips** [comment]
Would need to think a little about how to implement it. The ECHONET standard for the vertical swing mode doesn’t have an ‘auto’ option. The alternative is to use one of the other ECHONET swing settings like ‘’automatic swing selection’. This is kinda why the selects were implemented in the first place.

Could be possible to configure the preferred swing settings specific to the climate entity in the options but would need to figure out the best way of doing it, it’s a compromise between a massively long list and simplicity.





Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scottyphillips** [comment]
The ‘selects’ are there to overcome the inherit limitation in the climate class. Basically any swing mode of operation that your system supports should be available as a ‘select’ option outside of the normal swing setting of the climate entity. So you get all the auto settings + horizontal settings this way.

Scott

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Alfiegerner** [comment]
Okay thanks - it might be a use case for just turning the swing settings off for those entities, manage externally.  So then could be set to auto in Melview and just left.

**Comment by Alfiegerner** [comment]
@scottyphillips, thanks for you help and quick fixes. I'm all set up with my 5 heat pumps, will keep an eye on the logs and let you know how it goes.

What is these selects are meant to do:

![128652260-364e0e27-a23d-480d-9264-c105f1f93f31](https://user-images.githubusercontent.com/596188/128653872-a5e27504-8483-4e70-a577-4525c9bcf42e.png)

You mentioned something about the 'auto settings' above but tinkering with these hasn't done anything obvious for me.

**Comment by scottyphillips** [comment]
Excellent. Yes it was a bit of a mess putting it together, but the idea behind the current branch was to provide better support for all the folk out there that have multiple HVAC systems. The API has been streamlined so API call data is shared between sensors, climate, and the selects and it should play much better with Home Assistants asyncio underpinnings.. 

I can extend the logic that was used to create the 'options' to the other swing attributes as well. Should have something together in a day or two for you to test.

**Comment by Alfiegerner** [comment]
Yep those config changes look good. 

I think the auto ones are missing a 'not used' (or 'off') default value that would allow turn those modes off.  Also missing descriptions in the config to indicate what they are. 

But could to exclude not required options 👍

**Comment by scottyphillips** [comment]
I actually removed it as ‘not used’ confused the hell out of me. I will just add it back in.

 

Scott 

 

From: Alfiegerner ***@***.***>
Reply-To: scottyphillips/mitsubishi_hass ***@***.***>
Date: Wednesday, 11 August 2021 at 3:51 pm
To: scottyphillips/mitsubishi_hass ***@***.***>
Cc: Scott Phillips ***@***.***>, Mention ***@***.***>
Subject: Re: [scottyphillips/mitsubishi_hass] HELP NEEDED - Please test 'pychonet-2.0' branch (#29)

 

Yep those config changes look good.

I think the auto ones are missing a 'not used' (or 'off') default value that would allow turn those modes off. Also missing descriptions in the config to indicate what they are.

But could to exclude not required options 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alfiegerner** [comment]
Yeah the not used is a bit odd in some ways for a select list. It basically ends up as an on / off switch if you only have one swing mode.

The melview app has those modes as toggles, e.g. Auto position, on and off 
Swing mode, on and off.

**Comment by scottyphillips** [comment]
Yeah I’ll fix it up as best as I can but ‘not-used’ is how it is described in the Spec.

Scott

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iwarp** [comment]
I've just updated to this branch after getting it working with the main branch its reading my values ok. I did have one issue in the picture below but this was sorted once i deleted the original config, i was getting this error when adding the echonet integration.

![image](https://user-images.githubusercontent.com/20696463/129119793-85f07976-52a0-4052-828c-a58c224bc2d0.png)

**Comment by scottyphillips** [comment]
I suspect that the ‘pychonet’ library was running an older version at the time of the error and just needed time to pull the latest release from pip. Are you still seeing the issue now?

 

Regards,

 

Scott

 

 

 

From: iwarp ***@***.***>
Reply-To: scottyphillips/mitsubishi_hass ***@***.***>
Date: Thursday, 12 August 2021 at 10:21 am
To: scottyphillips/mitsubishi_hass ***@***.***>
Cc: Scott Phillips ***@***.***>, Mention ***@***.***>
Subject: Re: [scottyphillips/mitsubishi_hass] HELP NEEDED - Please test 'pychonet-2.0' branch (#29)

 

I've just updated to this branch after getting it working with the main branch its reading my values ok. I did have one issue in the picture below but this was sorted once i deleted the original config, i was getting this error when adding the echonet integration.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iwarp** [comment]
all working for me now i deleted the old config, restarted HA then i could add via the UI as per the readme. Just thought i would pass on my experience with the newer version!

**Comment by scottyphillips** [comment]
Much appreciate the feedback, please make me aware of any issues. 

 

Now that a few more people are using this branch, I’ll be more comfortable promoting it to master in a month or so.

 

Regards,

 

Scott Phillips

0477 735 482 

 

 

 

From: iwarp ***@***.***>
Reply-To: scottyphillips/mitsubishi_hass ***@***.***>
Date: Thursday, 12 August 2021 at 10:27 am
To: scottyphillips/mitsubishi_hass ***@***.***>
Cc: Scott Phillips ***@***.***>, Mention ***@***.***>
Subject: Re: [scottyphillips/mitsubishi_hass] HELP NEEDED - Please test 'pychonet-2.0' branch (#29)

 

all working for me now i deleted the old config, restarted HA then i could add via the UI as per the readme. Just thought i would pass on my experience with the newer version!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alfiegerner** [comment]
I had the issue as well with trying to use the old version with the new.  I was hoping initially to set one heatpump to pychonet and leave the others on the old version, but it wouldn't work - can't  remember the details now but remember some sort of incompatability.

**Comment by scottyphillips** [comment]
Thanks everyone who contributed to testing
