### ISSUE TITLE
HA Energy monitoring?

### ISSUE THREAD

**Issue by dmshimself** [scottyphillips/mitsubishi_hass#31]
IS there a way for the integration to provide energy usage to the new Energy Monitoring in HA?

**Comment by scottyphillips** [comment]
if someone puts in a PR then sure. The 'pychonet-2.0' branch will (should) create sensors for any supported ECHONETLite object, so in theory it could be built upon that.

Not going to be me sorry as the only ECHONET lite object I have to play around with is the HVAC.

**Comment by khcnz** [comment]
I haven't looked at the new Energy Monitoring API but I have been playing with the data my heatpump returns. One of the api call returns the total consumed KWH in 100WH increments. It's not quite instantaneous but it could be possible to interpolate the 100WH increments to try figure out an instantaneous rate when it's on.

**Comment by khcnz** [comment]
Energy usage is actually configured with energy (KWH) usage not power readings (KW), which I had originally assumed, despite the name...

![image](https://user-images.githubusercontent.com/130233/131929459-c308e6cf-e0ec-4ea2-bcd9-d2ee8eddb967.png)

The plus side of this, is that the used energy is returned (at least on my models)  in 100Wh increments
![image](https://user-images.githubusercontent.com/130233/131930148-4d582eee-3015-4da7-97e4-3fe799b1d054.png)
![image](https://user-images.githubusercontent.com/130233/131929809-b20202e3-66f7-4c5a-b98b-5a8a97bf133f.png)

So I plan on looking this up to long term energy statistics as well!

**Comment by scottyphillips** [comment]
I played around with the energy module in the 'moekadenroom' emulator, but i think you need to combine a number of EPCs together to come up with the energy readings..

That 0x85 value is probably the best best as it is an enduring value... 

The new library should be able to expose any ECHONETlite values as sensors...

**Comment by khcnz** [comment]
Just about, unfortunately 0x85 wasn't mapped in pychonet to a handler. PR incoming :)

**Comment by khcnz** [comment]
https://github.com/scottyphillips/pychonet/pull/6

**Comment by scottyphillips** [comment]
@khcnz will be taking over this project soon at this rate...

**Comment by khcnz** [comment]
I'm very happy being a supporter not a owner! I think we can close this issue now.

@dmshimself presuming you have a mitsubishi heatpump and it implements the correct codes, then if you delete and re-add your device after 2.0.11 is merged you'll have a cumulative energy sensor you can utilize with the new HA energy monitoring system.

**Comment by dmshimself** [comment]
Nice :-)  I'm looking forward to giving that a go.  Really appreciate the effort

**Comment by dmshimself** [comment]
The new integration burst into life with the 3 echonet entities working.  I'm gussing that as I cannot see anything else, then either 2.0.11 hasn't merged yet or my mitsubishi ducted system hasn't got or isn't configured with whatever is needed for the energy monitor to show. 

The HA core log shows the usual warning abut the integration not being one supported by HA, but I cannot see a version displayed.  I downloaded it about an hour ago.  Is there a way can can see what version is installed?

If it is 2.0.11, is there something I can put into AC installer terms to ask the company that did the install to come back and do whatever to let this energy sensor burst into life?

**Comment by karlchaffey** [comment]
Do you install it manually or through HACS? HACS doesn't have those changes published yet.

If you manually installed it from the master branch by downloading the code you can double check it worked by seeing if you have a manufacturer listed on the device page
![image](https://user-images.githubusercontent.com/37050858/132462595-4d28673b-167e-4d26-bf33-d1b5f6647426.png)

Alternatively If you also enabled debug mode for echonet the restart:
    custom_components.echonetlite: debug
    custom_components.echonetlite.sensor: debug
    custom_components.echonetlite.climate: debug
    custom_components.echonetlite.select: debug

you'll want to look for this in your logs
2021-09-07 17:58:18 DEBUG (MainThread) [custom_components.echonetlite.sensor] {'instance': {'host': '192.168.4.38', 'eojgc': 1, 'eojcc': 48, 'eojci': 1, 'getmap': [128, 160, 176, 129, 161, 130, 131, 163, 179, 164, 133, 165, 134, 136, 137, 138, 154, 139, 171, 187, 157, 158, 190, 143, 159],

and you need to have a value 133

**Comment by dmshimself** [comment]
I installed manually as per the current docs and I do indeed have manufacturer listed on the device page, so thats good.  The debug idea sounds interesting, but when I configure echonetlite or look through the contents of its folder, I cannot see how to set this debug up.  Could you do me the favoour of pointing to me how to set that up?

**Comment by khcnz** [comment]
Add something like this to your configuration.yaml file (not part of econet)

logger:
  default: warning
  logs:
    custom_components.echonetlite: debug
    custom_components.echonetlite.sensor: debug
    custom_components.echonetlite.climate: debug
    custom_components.echonetlite.select: debug

**Comment by dmshimself** [comment]
Perfect - thanks for that.  I get the data and I see no sign of a 133 as shown below :-(  Can I pose a general question.  Does this mean this Mitsubishi doesn't have this feature at all or could it be an option the installer didn't configure or one that I didn't know I needed to buy?  The installer was very helpful and if I know what to ask for, I might get a good result.  I know I coild put something like a Shelly EM in, but I'd like to see how far I can take this without.

2021-09-08 21:39:12 DEBUG (MainThread) [custom_components.echonetlite] Plaform entry data - {'instances': [{'host': '10.13.0.240', 'eojgc': 1, 'eojcc': 48, 'eojci': 1, 'getmap': [128, 160, 176, 129, 130, 131, 179, 134, 136, 137, 138, 187, 157, 158, 143, 159], 'setmap': [128, 129, 143, 160, 176, 179], 'uid': '0000060104a0c9a0fffe095236013001', 'manufacturer': 'Mitsubishi'}]}

**Comment by khcnz** [comment]
I think that's all but guaranteed that your unit doesn't support it and there is nothing you can do about that (unless perhaps they are firmware upgradable but i've never heard of that). My units are mitsubishi AP series wall units which are a 'newish' model.

**Comment by dmshimself** [comment]
Mine is 12 months old, but living in NZ we don't always get the latest gear here.  I really appreciate the guidance and it looks as though I'll be going along the Shelly route.

**Comment by droopanu** [comment]
hey @khcnz , are you happy with your energy readings from the heat pump?
Mine seem to be way too low on 2 AP series heatpumps. (50-100W even on full blast)

**Comment by khcnz** [comment]
Yea the readings are in **Watt Hours** not Watts. So you should see the cumulative number jumping around 100WH every few mins or so. If it was to jump 100WH every 120 seconds that would equate to 3KW running. Watt Hours are a measure of the total energy usage (not instantons) and is what HomeAssistant needs for it's energy tracking feature also.

I had a small console app looping and retrieving the value in a loop with 10second delays and I was getting results like this which shows the cumulative counter going up 100Wh in approx 84 seconds

![image](https://user-images.githubusercontent.com/130233/133004010-558af8c2-3dce-434b-b68b-9a0fbe96fbf0.png)

**Comment by droopanu** [comment]
hehehe, yeah. I was converting to W :D

Mine goes up 100W every hour or so.
![image](https://user-images.githubusercontent.com/7566514/133004189-cca8d15f-5e15-43bd-afe7-f74246808874.png)
![image](https://user-images.githubusercontent.com/7566514/133004262-9b3a64ca-2247-477e-b4c0-23373a400d24.png)


Almost looks like it only shows the indoor unit consumption only :(

Do you have that script somewhere so I could play with it?

**Comment by khcnz** [comment]
I haven't converted it to the new async but this might give you enough to go on along with the new async example in the pychonet 

```
import mitsubishi_echonet as mit
import time
from datetime import datetime

unit = mit.HomeAirConditioner(netif="ip address here")
lastPowerReading = unit.getCumulativePowerReading()
lastTimeReading = datetime.now()

while True:
    time.sleep(10)
    nextPowerReading = unit.getCumulativePowerReading()
    nextTimeReading = datetime.now()
    print(f"Total Cumlative Usage: {nextPowerReading}Wh")
    print(f"Period Cumulative Usage: {(nextPowerReading-lastPowerReading)}Wh")
    print(f"Av Instant Power: {(nextPowerReading-lastPowerReading)*60*6}W")
    print(f"Time Delta: {(nextTimeReading - lastTimeReading)}s")
    lastPowerReading = nextPowerReading
    lastTimeReading = nextTimeReading   
```

**Comment by khcnz** [comment]
Oh that code was slightly wrong but i can't find the example i had corrected, it should be storing the last time the value changed, and using that to calculate the number of seconds between updates to get the average power.

**Comment by khcnz** [comment]
My unit goes up by 100Wh about every two hours when off 
![image](https://user-images.githubusercontent.com/130233/133011977-c3a046ad-dc05-48ce-b3fc-01849ad7d185.png)

**Comment by droopanu** [comment]
Mine only goes up when on.
and then very slow even on full blast.:(

**Comment by khcnz** [comment]
I've just turned mine on to triple check, here you can see it is climbing fast after turning on

![image](https://user-images.githubusercontent.com/130233/133165748-14c1e34d-c8cd-485c-b6f2-74ba40cfcfe3.png)

I'm not quite sure where it would be going wrong, I have AP series also, it really does look like from your example it isn't on and just consuming 100Wh every few hours.

**Comment by droopanu** [comment]
out of curiosity, which AP series do you have?
I have one MSZ-AP35VGKD and one MSZ-AP42VGKD.

**Comment by khcnz** [comment]
One MSZ-AP25VGKD that is standalone internal unit and exterior pump and then one multi-unit with one exterior pump and internally 1x MSZ-AP50VGKD and 4x MSZ-AP22VGKD

Oh, I've been looking at this a little more, I can see on the multi unit all the heatpumps have energy graphs that seem to go up in the correct amounts when the unit is on, but on the standalone MSZ-AP25VGKD it is not, and seems to go up a small amount like your screenshot. I'll take a deeper look into this device tonight.

**Comment by droopanu** [comment]
Maybe those heatpumps really use that little energy?
lol

**Comment by Zerosignal84** [comment]
> One MSZ-AP25VGKD that is standalone internal unit and exterior pump and then one multi-unit with one exterior pump and internally 1x MSZ-AP50VGKD and 4x MSZ-AP22VGKD
> 
> Oh, I've been looking at this a little more, I can see on the multi unit all the heatpumps have energy graphs that seem to go up in the correct amounts when the unit is on, but on the standalone MSZ-AP25VGKD it is not, and seems to go up a small amount like your screenshot. I'll take a deeper look into this device tonight.

khcnz, did you ever find a solution to this? I've noticed the same issue as yourself with that model.

I presume that this might be a datalogging issue on the device itself rather than something that can be solved with the script?

**Comment by droopanu** [comment]
Hi,

The official app has added energy monitoring. And based on that it looks like some units report every 550Wh while other units report every 100Wh.

**Comment by Zerosignal84** [comment]
> Hi,
> 
> The official app has added energy monitoring. And based on that it looks like some units report every 550Wh while other units report every 100Wh.

Yeah but the energy usage that is reported or interpreted is way too low, my 9kwh standalone used less power than my NAS today according to home assistant.

I'm guessing it is a problem on the mitsubishi end, I tried playing around with Pychonet myself yesterday but I'm just not familar enough with the coding language to get it going properly.

**Comment by droopanu** [comment]
You can create a template sensor like this: 

{{ states("sensor.office_heatpump_measured_cumulative_power_consumption") |float*5.75}}

This will give you the real energy usage of the Heatpump

**Comment by Zerosignal84** [comment]
> "sensor.office_heatpump_measured_cumulative_power_consumption") |float*5.75}}

Thanks for the response, I will use this and see how it goes - just so I learn something here why the multiplication factor of 5.75?

Really appreciate you getting back to me.

**Comment by droopanu** [comment]
I got it from the official Mitsubishi app.

**Comment by Zerosignal84** [comment]
Mitsubishi Electric in New Zealand just released this for the Melview app in September.

https://www.mitsubishi-electric.co.nz/materials/Controllers/Manuals/Wi-Fi/1_Operation/Guide_Wi-Fi_Energy_Monitoring.pdf

Does not seem applicable to the Australian version just yet.

**Comment by droopanu** [comment]
Basically each unit reported by some Heatpumps is 575wh while for others is
100wh.

Echonet can not make that distinction and actually reports 100wh for all
devices.

**Comment by Zerosignal84** [comment]
Thanks Droopanu.

For those interested in the Melview energy page, it is located here https://app.melview.net/energy.html

It will not load for my devices but I can force it to but no data is showing.

**Comment by droopanu** [comment]
I'm in New Zealand and I have that version on the app. It shows me only the
yellow bars (indicative energy view) for all my units.
But for someunits I get the 100wh units while for others I get the 525wh
units...

**Comment by julianjwong** [comment]
Oops! Looks like I created helper entities. Ignore :)
