### ISSUE TITLE
Home Assistant Climate Integration Steals Heat Pump

### ISSUE THREAD

**Issue by ChirpyTurnip** [scottyphillips/mitsubishi_hass#33]
Hi,

So I'm not really sure this is an Echonet problem...but I'm also not sure where else to begin....it has been working fine for a couple of months (since I last posted) but suddenly in the space of a week I've lost two heat pumps to the 'native' climate integration. Basically the heat pump becomes 'unavailable' in Lovelace and on investigation a second entity is created in HA. First it was my hallway heatpump, now my lounge  has done the same. 

The original entity was "climate.lounge_heat_pump" provided by "mitsubishi". A new one has now appeared called "climate.lounge_heat_pump_2" but in this case provided by "climate"....you can view it but it is not possible to make any changes to it (e.g. disable it) because of the usual "does not have a unique ID, therefore its settings cannot be managed from the UI".

I don't know why these 'additional' entities get created....but when they do the Mitsubishi Echonet integration can't function....  :-(

I wonder if it is because there is a bug in the integration, or in the newer version of HA (I'm running the latest version of HA Supervised). And, to be honest, I wouldn't have a clue as to where to start debugging this...  :-(

**Comment by ChirpyTurnip** [comment]
If it helps, the fix is to comment out the integration for the failed heatpump in the configuraiton.yaml, restart HA, then remove the comment hashing, and restart again - then the "climate.lounge_heat_pump_2" vanishes and the original "climate.lounge_heat_pump" just starts working again....

It's just weird.

**Comment by scottyphillips** [comment]
I am not working on the original code anymore, but i need more people to test the new pychonet-2.0 branch. Please download that branch and let me know of any issues there
