### ISSUE TITLE
Long Term Stats

### ISSUE THREAD

**Issue by khcnz** [scottyphillips/mitsubishi_hass#35]
Hey @scottyphillips 

FYI I'm planning to implement these small changes in a PR soonish to let the temperature sensors work for long term stats :)

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by scottyphillips** [comment]
Lets do this.

**Comment by khcnz** [comment]
Draft here :)

https://github.com/scottyphillips/mitsubishi_hass/pull/37

**Comment by khcnz** [comment]
Implemented and merged.
