### ISSUE TITLE
Later version of Home assistant core not being recognised

### ISSUE THREAD

**Issue by Ledfoot775** [scottyphillips/mitsubishi_hass#36]
hey Scott- Long time Mitsubishi user, super happy with what you've done!

Just doing a re-install, and found there is an error somewhere in the minimum version required for HACS to maintain. 

specific error: 
`You are running Home Assistant version '2021.9.2', but this repository requires minimum version 'core-2021.7.2' to be installed.`

I'll do it manually but any chance you could update this so I can easily keep up with any changes?

![image](https://user-images.githubusercontent.com/52377009/132093123-3e8458a6-fdef-4804-939f-9b5cd1149e0b.png)

**Comment by scottyphillips** [comment]
That is more a problem with HACS to be honest. It doesn't help that Home Assistant has a long habit of making annoying little breaking changes like that.
