### ISSUE TITLE
Small issues with instructions

### ISSUE THREAD

**Issue by tjharman** [scottyphillips/mitsubishi_hass#4]
Hi,

The instructions state:

1.     Using the tool of choice open the directory (folder) for your HA configuration (where you find configuration.yaml).
2.     If you do not have a custom_components directory (folder) there, you need to create it.
3.     In the custom_components directory (folder) create a new folder called blueprint.
4.     Download all the files from the custom_components/mitsubishi/ directory (folder) in this repository.
5.     Place the files you downloaded in the new directory (folder) you created.
6.     Restart Home Assistant
7.     Add mitsubishi: to your HA configuration.

I think step 3 is wrong - where it says "blueprint" it should say "mitsubishi"

Also I'm not 100% the mitsubishi: in step 7 is necessary or working?  I get the following error on starting hass with it:

`[homeassistant.setup] Setup failed for mitsubishi: No setup function defined.
`
My hass version is 0.101.3

I do however have the whole thing working perfectly, for which I'm very grateful!

**Comment by scottyphillips** [comment]
Thanks mate, I’ll fix up the instructions probably a slack copy/paste job on my part.

On 19 Nov 2019, at 7:06 am, Tim Harman <notifications@github.com> wrote:

﻿

Hi,

The instructions state:

  1.

Using the tool of choice open the directory (folder) for your HA configuration (where you find configuration.yaml).


  2.

If you do not have a custom_components directory (folder) there, you need to create it.


  3.

In the custom_components directory (folder) create a new folder called blueprint.


  4.

Download all the files from the custom_components/mitsubishi/ directory (folder) in this repository.


  5.

Place the files you downloaded in the new directory (folder) you created.


  6.

Restart Home Assistant


  7.

Add mitsubishi: to your HA configuration.


I think step 3 is wrong - where it says "blueprint" it should say "mitsubishi"

Also I'm not 100% the mitsubishi: in step 7 is necessary or working? I get the following error on starting hass with it:

[homeassistant.setup] Setup failed for mitsubishi: No setup function defined.

My hass version is 0.101.3

I do however have the whole thing working perfectly, for which I'm very grateful!

**Comment by scottyphillips** [comment]
Fixed up instructions
