### ISSUE TITLE
Feature: Power on to previous "mode" setting

### ISSUE THREAD

**Issue by Ledfoot775** [scottyphillips/mitsubishi_hass#5]
_As a user, I want the aircon to return to the previous settings when I send a turn on request, because I usually don't change the settings during a season._

First up - great work and thanks for solving a big problem for me!  

Note my primary use case is Siri voice control via HomeKit.

Prior to adding this to HA, my IR remote would be set at a particular temperature, and either in heating or cooling mode. This means every time I turn the split on it would go back to the same temperature, mode (auto/heat/cool/dry) and fan selection as it was before.

Currently when the command is sent to just turn the unit "on", temperature is remembered and so was the previous fan setting - but the mode goes to "auto" (when it was previously cooling or heating)

What I would like is an option where the unit powers back to its previous setting. For example if it was set to cooling when it was turned off, it would return to that when turned on.

**Comment by scottyphillips** [comment]
Hi Ledfoot. 

Are you able to clarify exactly how you are sending the command to turn the air conditioner on? is that via a service call in Home assistant? Or is this via the HomeKit Add-on? 

It is not something that I am able to replicate at present. On my own Home Assistant system if I execute the following steps:
1. Go to Developer Tools -> services
2. call service -> climate.turn_on

Then on my own system it returns the last used mode (which in my case was "cooling"). Its certainly not returning 'auto' 

For the purposes of debugging this issue, in the HASS code all the API call does for "on" is call the  corresponding ECHONET "On" call. (line) 

It possibly might have something to do with the init code (line 95) which defaults the HVAC mode to 'auto' if the ECHONET API call does not return the 'mode' key/value pair. 

Ill keep playing around and see if I can replicate the behaviour.

**Comment by scottyphillips** [comment]
Ive made some minor changes to the component to properly enable 'auto' mode when using HomeKit.

**Comment by scottyphillips** [comment]
Actually, it might be behaviour of Siri/Homekit... I just requested Siri to 'turn the air conditioner on' and it set the AC to 'auto'

**Comment by Ledfoot775** [comment]
Hey Scotty,

Thanks for looking into that for me - and you're spot on. Asking Siri to set "cool" or "heat does the job. In my case its called the "Lounge Aircon" so "Lounge Aircon Cool" sorts it out!

Thanks again for writing the component, I've got 3 other Mitsubishi splits in the house which I'm going to wire up now.

Have a great year!
