### ISSUE TITLE
Control aircon by half degrees

### ISSUE THREAD

**Issue by Smithey** [scottyphillips/mitsubishi_hass#8]
Is it possible to control the aircon by half a degree?

I can do it via the mitsubishi app however from home assistant when I try set it to a half degree it will just round down to the nearest degree.

**Comment by scottyphillips** [comment]
Not possible with the ECHONET library sorry. It returns an integer value only, not a floating value. Believe me I have tried...

**Comment by scottyphillips** [comment]
Reopening this issue to remind myself to update the climate entity to use whole degrees only..

**Comment by scottyphillips** [comment]
Closing this again because even though I have played around with precision values in HA it doesn't seem to work.
