### ISSUE TITLE
Zones

### ISSUE THREAD

**Issue by stuarts0011** [scottyphillips/mitsubishi_hass#9]
I couldn't see any reference to zone control commands in the specification. Have you looked into this? 

Edit: I looked through the Echolite specification for homeairconditioner ( https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/Release/Release_F_en/SpecAppendixF_e.pdf ) and there doesn't seem to be any setting for this. But it is implemented in the Mitsubishi app so that seems strange?

**Comment by scottyphillips** [comment]
The ECHONET API unfortunately is not as feature rich as the internal functionality of the Mitsubishi iphone app. The trade off is you get complete local control over your system. However if you need zone functionality then maybe ask the maintainer of the ‘melview’ integration and see what they can do. Of course that means you need to go to cloud polling. It could be possible to create switches using melview for the zones and use this integration for the rest of the aircon control. 

My zones are not integrated into the HVAC (which to be honest is annoying) so I don’t have enough of a reason to look into it.  

FYI please check closed issues as I have already answered this question once before.
